export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const LOGOUT = 'LOGOUT';
export const VIEWPRODUCT = 'VIEWPRODUCT';
export const FILTEREDPRODUCTS = 'FILTEREDPRODUCTS'
export const VIEWALLPRODUCT = 'VIEWALLPRODUCT'